### ISSUE TITLE
Allow more lines on scenario examples

### ISSUE THREAD

**Issue by ehannes** [backus/rubocop-rspec#210]
I know I can set the allowed length of examples with:
```
RSpec/ExampleLength:
  Max: 19
```
Would it be possible to implement a specific limit to scenario examples (those examples used in feature specs)? For performance reason, especially when testing JavaScript, I tend to allow more than one example per scenario. Something like this:
```
RSpec/ExampleLength:
  Max: 5
RSpec/ScenarioLength:
  Max: 20
```

**Comment by backus** [comment]
I'd be open to something like that (ideally not a totally new cop). I don't use scenarios so I probably wont implement that in my free time but if you want to propose a specific implementation solution I'd be fine with accepting a PR for this

**Comment by ehannes** [comment]
If one would like to implement this, where would you start?

**Comment by ehannes** [comment]
This issue also concerns `RSpec/MultipleExpectations`.

**Comment by backus** [comment]
This is actually an issue for many of our cops (and I haven't been sure how to improve rubocop-rspec to fit the various use cases) so how do you feel about something like this:

```yml
---
AllCops:
  RSpec:
    Patterns:
    - _spec.rb
    - "(?:^|/)spec/"
    SpecTypes:
      Feature: 'spec/features/**/*'
      Unit: 'spec/unit/**/*'
      Scenario: 'spec/scenario/**/*'

# ...

RSpec/ExampleLength:
  Description: Checks for long examples.
  Enabled: true
  Max: 5
  SpecType:
    Feature:
      Max: 10
    Scenario:
      Max: 10
```

The idea here is that you could specify any arbitrary mapping of a spec type name to a file glob in the `AllCops/RSpec/SpecTypes` section. Then, in a cop that supports spec type overrides, you could use those spec type names you defined to define settings for just that part of your application. Seems like this would solve a lot more problems than adding new slightly different cops would.

@ehannes @bquorning @andyw8 thoughts on this approach?

**Comment by bquorning** [comment]
As I recall it, `rspec-rails` will tag your specs with a type tag, e.g. `type: :feature`, `type: :controller`, `type: :view` etc. I wonder if these types could be used for the mapping you’re looking for.

I realize that not all people use RSpec together with Rails, so perhaps this is a bad suggestion.

**Comment by ehannes** [comment]
@bquorning Good point. It's true that `rspec-rails` uses types in specs (see [rspec-rails Directory Structure](https://www.relishapp.com/rspec/rspec-rails/docs/directory-structure)). It would be sad if this this gem was dependent on `rspec-rails`, so the question is if you can use this feature in `rspec` as well. I have not tried yet, but I found that you can add `type: :special` to specific examples in `rspec` (see [rspec `--tag` option] (http://www.relishapp.com/rspec/rspec-core/v/3-5/docs/command-line/tag-option)).

**Comment by bquorning** [comment]
You can add metadata based on directory structure using `config.define_derived_metadata`: http://www.rubydoc.info/gems/rspec-core/RSpec%2FCore%2FConfiguration%3Adefine_derived_metadata

I guess the question is whether we want to force part of the configuration into people’s `spec_helper.rb` instead of their `.rubocop.yml`.

**Comment by ehannes** [comment]
I tried the following:

``` ruby
# spec/support/integration_helper.rb
module IntegrationHelper
  # Includes things that integration tests need
end
```

``` ruby
# spec/integrations/test_class_spec.rb
describe TestClass, type: :integration do
  # Some examples that need IntegrationHelper
end
```

``` ruby
# spec/spec_helper.rb
RSpec.configure do |config|
# ...
  config.include IntegrationHelper, type: :integration
# ...
end
```

And it works like a charm.

**Comment by ehannes** [comment]
I would rather add `type: :whatever` as I please to my specs than be forced to set that specific configuration in `spec_helper.rb`. Also, some users may use the `type` metadata for something else and forcing them to set the type according to the directory structure may break things for them.

**Comment by ehannes** [comment]
If you use `type`, I guess you would get a `.rubocop.xml` file that looks something like this:
```
...
    SpecTypes:
      Feature: :feature
      Unit: :unit
      Whatever: :whatever
```
