### ISSUE TITLE
errors while running DescribedClass cop?

### ISSUE THREAD

**Issue by chrishough** [backus/rubocop-rspec#314]
**Spec**
```
RSpec/DescribedClass:
  Description: Checks that tests use `described_class`.
  SkipBlocks: false
  Enabled: true
  EnforcedStyle: described_class
  SupportedStyles:
    - described_class
    - explicit
```
**Error**
```
Warning: unrecognized parameter RSpec/DescribedClass:EnforcedStyle found in /Users/chrishough/Code/RobotsBuildingRobots/clients/kisoils/mws-sales/.rubocop_rspec.yml
Warning: unrecognized parameter RSpec/DescribedClass:SupportedStyles found in /Users/chrishough/Code/RobotsBuildingRobots/clients/kisoils/mws-sales/.rubocop_rspec.yml
undefined method `include?' for nil:NilClass
/Users/chrishough/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/config.rb:291:in `block in validate_enforced_styles'
/Users/chrishough/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/config.rb:288:in `each'
/Users/chrishough/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/config.rb:288:in `validate_enforced_styles'
/Users/chrishough/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/config.rb:169:in `validate'
/Users/chrishough/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/config_loader.rb:49:in `load_file'
/Users/chrishough/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/config_loader.rb:89:in `block in base_configs'
/Users/chrishough/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/config_loader.rb:77:in `map'
/Users/chrishough/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/config_loader.rb:77:in `base_configs'
/Users/chrishough/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/config_loader_resolver.rb:21:in `resolve_inheritance'
/Users/chrishough/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/config_loader.rb:39:in `load_file'
/Users/chrishough/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/config_loader.rb:105:in `configuration_from_file'
/Users/chrishough/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/config_store.rb:44:in `for'
/Users/chrishough/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cli.rb:93:in `apply_default_formatter'
/Users/chrishough/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/lib/rubocop/cli.rb:25:in `run'
/Users/chrishough/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/bin/rubocop:13:in `block in <top (required)>'
/Users/chrishough/.rbenv/versions/2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/Users/chrishough/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.46.0/bin/rubocop:12:in `<top (required)>'
/Users/chrishough/.rbenv/versions/2.3.3/bin/rubocop:22:in `load'
/Users/chrishough/.rbenv/versions/2.3.3/bin/rubocop:22:in `<main>'
```
I like to use the full configuration and rollback from there to mentor others.  Not sure what is causing this but I am happy to help. Using the file from https://github.com/backus/rubocop-rspec/issues/313.

**Comment by backus** [comment]
You probably have to upgrade to rubocop 0.47. Since there is no official third party API we currently have to roll out changes to match their changes. Can you let me know if that works?

**Comment by chrishough** [comment]
This error passes, however, it looks like they made a number of changes...
```
Warning: unrecognized parameter RSpec/DescribedClass:EnforcedStyle found in /Users/chrishough/Code/RobotsBuildingRobots/clients/kisoils/mws-sales/.rubocop_rspec.yml
Warning: unrecognized parameter RSpec/DescribedClass:SupportedStyles found in /Users/chrishough/Code/RobotsBuildingRobots/clients/kisoils/mws-sales/.rubocop_rspec.yml
Warning: unrecognized parameter Style/SpaceAroundBlockParameters:SupportedStyles found in /Users/chrishough/Code/RobotsBuildingRobots/clients/kisoils/mws-sales/.rubocop.yml
Warning: unrecognized parameter Style/TrailingCommaInArguments:SupportedStyles found in /Users/chrishough/Code/RobotsBuildingRobots/clients/kisoils/mws-sales/.rubocop.yml
Warning: unrecognized parameter Style/TrailingCommaInLiteral:SupportedStyles found in /Users/chrishough/Code/RobotsBuildingRobots/clients/kisoils/mws-sales/.rubocop.yml
Warning: unrecognized parameter Lint/EndAlignment:SupportedStyles found in /Users/chrishough/Code/RobotsBuildingRobots/clients/kisoils/mws-sales/.rubocop.yml
Warning: unrecognized parameter Lint/DefEndAlignment:SupportedStyles found in /Users/chrishough/Code/RobotsBuildingRobots/clients/kisoils/mws-sales/.rubocop.yml
Warning: unrecognized parameter RSpec/DescribedClass:EnforcedStyle found in /Users/chrishough/Code/RobotsBuildingRobots/clients/kisoils/mws-sales/.rubocop.yml
Warning: unrecognized parameter RSpec/DescribedClass:SupportedStyles found in /Users/chrishough/Code/RobotsBuildingRobots/clients/kisoils/mws-sales/.rubocop.yml
```

**Comment by backus** [comment]
Do you have a `require: rubocop-rspec` at the top of your main config file?

**Comment by chrishough** [comment]
Yep :(

**Comment by backus** [comment]
Can you share your config files as well as the versions of rubocop and rubocop-rspec you are using?

**Comment by chrishough** [comment]
my rspec yml...
```
# Review the detailed rspec cops here!
# https://github.com/backus/rubocop-rspec
AllCops:
  RSpec:
    Patterns:
      - _spec.rb
      - "(?:^|/)spec/"

RSpec/AnyInstance:
  Description: Check that instances are not being stubbed globally.
  Enabled: true

RSpec/BeEql:
  Description: Check for expectations where `be(...)` can replace `eql(...)`.
  Enabled: true

RSpec/DescribeClass:
  Description: Check that the first argument to the top level describe is a constant.
  Enabled: true
  Exclude:
    - spec/lib/tasks/*

RSpec/DescribedClass:
  Description: Checks that tests use `described_class`.
  SkipBlocks: false
  Enabled: true
  EnforcedStyle: described_class
  SupportedStyles:
    - described_class
    - explicit

RSpec/DescribeMethod:
  Description: Checks that the second argument to `describe` specifies a method.
  Enabled: true

RSpec/EmptyExampleGroup:
  Description: Checks if an example group does not include any tests.
  Enabled: true
  CustomIncludeMethods: []

RSpec/ExampleLength:
  Description: Checks for long examples.
  Enabled: true
  Max: 5

RSpec/ExampleWording:
  Description: Checks that example descriptions do not start with "should".
  Enabled: true
  CustomTransform:
    be: is
    have: has
    not: does not
  IgnoredWords: []

RSpec/ExpectActual:
  Description: Checks for `expect(...)` calls containing literal values.
  Enabled: true

RSpec/ExpectOutput:
  Description: Checks for opportunities to use `expect { ... }.to output`.
  Enabled: true

RSpec/FilePath:
  Description: Checks that spec file paths are consistent with the test subject.
  Enabled: true
  CustomTransform:
    RuboCop: rubocop
    RSpec: rspec
  IgnoreMethods: false

RSpec/Focus:
  Description: Checks if examples are focused.
  Enabled: true

RSpec/HookArgument:
  Description: Checks the arguments passed to `before`, `around`, and `after`.
  Enabled: true
  EnforcedStyle: implicit
  SupportedStyles:
    - implicit
    - each
    - example

RSpec/ImplicitExpect:
  Description: Check that a consistent implicit expectation style is used.
  Enabled: true
  EnforcedStyle: is_expected
  SupportedStyles:
    - is_expected
    - should

RSpec/InstanceVariable:
  Description: Checks for instance variable usage in specs.
  AssignmentOnly: false
  Enabled: true

RSpec/LeadingSubject:
  Description: Checks for `subject` definitions that come after `let` definitions.
  Enabled: true

RSpec/LetSetup:
  Description: Checks unreferenced `let!` calls being used for test setup.
  Enabled: true

RSpec/MessageChain:
  Description: Check that chains of messages are not being stubbed.
  Enabled: true

RSpec/MessageExpectation:
  Description: Checks for consistent message expectation style.
  Enabled: false
  EnforcedStyle: allow
  SupportedStyles:
    - allow
    - expect

RSpec/MessageSpies:
  Description: Checks that message expectations are set using spies.
  Enabled: true
  EnforcedStyle: have_received
  SupportedStyles:
    - have_received
    - receive

RSpec/MultipleDescribes:
  Description: Checks for multiple top level describes.
  Enabled: true

RSpec/MultipleExpectations:
  Description: Checks if examples contain too many `expect` calls.
  Enabled: true
  Max: 1

RSpec/NamedSubject:
  Description: Checks for explicitly referenced test subjects.
  Enabled: true

RSpec/NestedGroups:
  Description: Checks for nested example groups.
  Enabled: true
  Max: 5

RSpec/NotToNot:
  Description: Checks for consistent method usage for negating expectations.
  EnforcedStyle: not_to
  SupportedStyles:
    - not_to
    - to_not
  Enabled: true

RSpec/RepeatedDescription:
  Enabled: true
  Description: Check for repeated description strings in example groups.

RSpec/RepeatedExample:
  Enabled: true
  Description: Check for repeated examples within example groups.

RSpec/SingleArgumentMessageChain:
  Description: Checks that chains of messages contain more than one element.
  Enabled: true

RSpec/ScatteredSetup:
  Description: Checks for setup scattered across multiple hooks in an example group.
  Enabled: true

RSpec/SubjectStub:
  Description: Checks for stubbed test subjects.
  Enabled: true

RSpec/VerifiedDoubles:
  Description: Prefer using verifying doubles over normal doubles.
  Enabled: true
  IgnoreSymbolicNames: false
```
my rubocop yml
```
require: rubocop-rspec
# Review the detailed linter docs here!
# http://rubocop.readthedocs.io/en/latest/
inherit_from: .rubocop_rspec.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - 'Guardfile'
    - 'config/initializers/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'scratch.rb'
    - 'lib/assets/**/*'
    - '*.yml'
Rails:
  Enabled: true
```

```
    rubocop (0.47.1)
      parser (>= 2.3.3.1, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.0, >= 1.0.1)
    rubocop-rspec (1.10.0)
      rubocop (>= 0.42.0)
```

**Comment by chrishough** [comment]
It looks like these changed on the rubocop side...
```
RSpec/DescribedClass:
  Description: Checks that tests use `described_class`.
  SkipBlocks: false
  Enabled: true
  EnforcedStyleForMultiline: described_class
  SupportedStylesForMultiline:
    - described_class
    - explicit
```

**Comment by backus** [comment]
Odd. I can't reproduce on a project of mine. I noticed though that you have configuration warnings for rubocop proper as well. Maybe worth reporting there?

**Comment by backus** [comment]
> It looks like these changed on the rubocop side...

`RSpec/DescribedClass` never had configuration named `EnforcedStyleForMultiline`

**Comment by chrishough** [comment]
I fixed those by updating them to the latest.

**Comment by chrishough** [comment]
This is what I have now there and it tosses warnings... 
```

RSpec/DescribedClass:
  Description: Checks that tests use `described_class`.
  SkipBlocks: false
  Enabled: true
  EnforcedStyle: described_class
  SupportedStyles:
    - described_class
    - explicit
```

and now I am seeing these in `Metrics/BlockLength: Block has too many lines.`
