### ISSUE TITLE
RSpec/ContextWording: Start context description with 'without'

### ISSUE THREAD

**Issue by mickael-palma-argus** [backus/rubocop-rspec#500]
Hi,

It is not covering the 'without' case.

Here is my rubocop config :

rubocop-rspec (1.20.0)

```
require: rubocop-rspec

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/BlockLength:
  ExcludedMethods:
    - api_version
    - context
    - define
    - describe
    - draw
    - factory
    - group
    - guard
    - included # For Concerns
    - namespace
    - trait

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'features/**/*'
    - 'lib/tasks/*'

```

How can I restore the proper behaviour ?

https://github.com/backus/rubocop-rspec/blob/ed17114fe70b98cd18dbb9a473f40687c772b82d/lib/rubocop/cop/rspec/context_wording.rb#L11
